<a href="https://colab.research.google.com/github/shankarvk2006/tns_learn/blob/main/MVIT_Batch_3____AI_%26_ML____NumPy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy (Array Operations)

**NumPy** (Numerical Python) is a powerful library used for working with multi-dimensional arrays, performing fast mathematical operations, and manipulating large datasets efficiently.

### Characteristics:

* **ndarray:** The core data structure, representing an N-dimensional array.
* **Vectorized Operations:** Performs element-wise operations rapidly without slow explicit loops.
* **Homogeneous:** Stores elements of the same data type for high memory efficiency.

---

### Core Operations:

| Category | Function | Usage |
| :--- | :--- | :--- |
| **Creation** | `np.array()` | Create an array from a Python list |
| | `np.arange(start, stop, step)` | Create an array with a sequence/range of numbers |
| | `np.zeros((m,n))` / `np.ones((m,n))` | Create an array filled with 0s or 1s |
| | `np.eye(n)` | Create an $n \times n$ Identity Matrix |
| | `np.linspace(start, stop, num)` | Create evenly spaced numbers over a specified interval |
| | `np.random.rand(m,n)` | Generate random numbers between 0 and 1 |
| **Shape & Reshape** | `arr.shape` | Get dimensions/shape of an array |
| | `arr.reshape(rows, cols)` | Change array dimensions without altering data |
| | `np.transpose(arr)` | Transpose rows into columns (`arr.T`) |
| **Aggregations** | `np.sum()`, `np.mean()`, `np.std()` | Calculate total sum, average, and standard deviation |
| | `np.min()`, `np.max()` | Find smallest and largest values |
| | `np.argmin()`, `np.argmax()` | Find the index of smallest and largest values |
| **Linear Algebra & Utility** | `np.dot()`, `np.matmul()` | Perform matrix multiplication |
| | `np.sort()` | Return a sorted copy of an array |

---

1. Creating Arrays

In [ ]:
import numpy as np

# Create an array from a list
a = np.array([10, 20, 30])
print("Array:", a)

# Range of numbers (Start, Stop, Step)
b = np.arange(1, 6)
print("Range:", b)               # [1 2 3 4 5]

# Array of Zeros
c = np.zeros((2, 2))
print("Zeros:\n", c)

# Array of Ones
d = np.ones((2, 2))
print("Ones:\n", d)

# Identity Matrix
e = np.eye(3)
print("Identity Matrix:\n", e)

# Evenly spaced numbers (Start, Stop, Count)
f = np.linspace(0, 10, 5)
print("Linspace:", f)            # [ 0.   2.5  5.   7.5 10. ]

# Random numbers between 0 and 1
g = np.random.rand(2, 2)
print("Random:\n", g)

Array: [10 20 30]
Range: [1 2 3 4 5]
Zeros:
 [[0. 0.]
 [0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Linspace: [ 0.   2.5  5.   7.5 10. ]
Random:
 [[0.27945213 0.80345379]
 [0.24897098 0.58422822]]


2. Shape, Reshape & Transpose

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

# Get shape (dimensions)
print("Shape:", arr.shape)       # Output: (6,)

# Reshape into 2 rows and 3 columns
matrix = arr.reshape(2, 3)
print("Reshaped (2x3):\n", matrix)

# Transpose (Swap rows and columns)
print("Transposed:\n", np.transpose(matrix))

Shape: (6,)
Reshaped (2x3):
 [[1 2 3]
 [4 5 6]]
Transposed:
 [[1 4]
 [2 5]
 [3 6]]


3. Math & Aggregations

In [ ]:
import numpy as np

nums = np.array([10, 40, 20, 50, 30])

# Basic stats
print("Sum:", np.sum(nums))      # 150
print("Mean:", np.mean(nums))    # 30.0
print("Std Dev:", np.std(nums))  # Standard deviation

# Min and Max values
print("Min Value:", np.min(nums)) # 10
print("Max Value:", np.max(nums)) # 50

# Index position of Min and Max
print("Min Index:", np.argmin(nums)) # 0 (index of 10)
print("Max Index:", np.argmax(nums)) # 3 (index of 50)

Sum: 150
Mean: 30.0
Std Dev: 14.142135623730951
Min Value: 10
Max Value: 50
Min Index: 0
Max Index: 3


4. Matrix Operations & Sorting

In [ ]:
import numpy as np

# Matrix Multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = np.matmul(A, B)
print("Matrix Multiplication:\n", result)

# Sorting an Array
unsorted = np.array([40, 10, 30, 20])
print("Sorted Array:", np.sort(unsorted)) # [10 20 30 40]

Matrix Multiplication:
 [[19 22]
 [43 50]]
Sorted Array: [10 20 30 40]
